CatchmeBundle\Entity\Challenge:
    type: entity
    table: null
    repositoryClass: CatchmeBundle\Repository\ChallengeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: '30'
        description:
            type: text
            nullable: true
        localisation:
            type: string
            length: '30'
        longitude:
            type: float
        latitude:
            type: float
    manyToMany:
            image:
                targetEntity: CatchmeBundle\Entity\Image
                joinTable:
                  name: images_challenges
                  joinColumns:
                    images_id:
                      referencedColumnName: id
                  inverseJoinColumns:
                    challenges_id:
                      referencedColumnName: id
    lifecycleCallbacks: {  }
