# src/CatchmeBundle/Resources/config/doctrine/Group.orm.yml
CatchmeBundle\Entity\Group:
    type:  entity
    table: fos_group
    id:
        id:
            type: integer
            generator:
                strategy: AUTO