CatchmeBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: CatchmeBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        url:
            type: text

    manyToOne:
        users:
            targetEntity: CatchmeBundle\Entity\User

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
