CatchmeBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        score:
            type: integer
            nullable: true

    manyToOne:
        image:
            targetEntity: CatchmeBundle\Entity\Image
            nullable: true
            cascade: ["persist", "remove"]

    manyToMany:
        challenges:
            targetEntity: CatchmeBundle\Entity\Challenge
            nullable: true
            inversedBy: users
            joinColumns:
                name: group_challenge

    lifecycleCallbacks: {  }



