CatchmeBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToOne:
        image:
            targetEntity: CatchmeBundle\Entity\Image
            cascade: ["persist", "remove"]
    lifecycleCallbacks: {  }

    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id

