# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

#   Surcharge du registration form type de fosuser
    app.form.registration:
        class: CatchmeBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }

    redirect.after.login:
        class: CatchmeBundle\Redirection\AfterLoginRedirection
        arguments: [@router]

##   Service de redirection après le login en fonction des roles
#    redirect.after.login:
#        class: TR\MainBundle\Redirection\AfterLoginRedirection
#        arguments: [@router, @doctrine.orm.entity_manager]

fos_user:
    registration:
        form:
            type: app_user_registration

