<?php

namespace CatchmeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageMetadataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageMetadateRepository extends EntityRepository
{

}