<?php

namespace CatchmeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ThreadMetadata Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadMetadataRepository extends EntityRepository
{

}